import {
  EventPriorityStatus,
  EventProgressStatus,
  EventStatus,
  FestivalEventStatus,
  MiscellaneousEventStatus,
  PersonalEventStatus,
  ProfessionalEventStatus,
  ReminderModal,
  SocialEventStatus,
} from "./EnumAndOptions";

export const eventJsonList = [
  {
    id: 1,
    eventType: EventProgressStatus.PERSONAL_EVENTS,
    customEvent: PersonalEventStatus.BIRTHDAY,
    date: "2025-07-30 21:00:00",
    priority: EventPriorityStatus.LOW,
    description: "lorem10",
    isReminedMe: ReminderModal.TRUE,
    eventStatus: EventStatus.COMPLETED,
  },

  {
    id: 2,
    eventType: EventProgressStatus.FESTIVALS_RELIGIOUS_EVENTS,
    customEvent: FestivalEventStatus.EID_EIDUL_ADHA,
    date: "2025-08-10 18:15:00",
    priority: EventPriorityStatus.HIGH,
    description: "Attend a meeting",
    isReminedMe: ReminderModal.FALSE,
    eventStatus: EventStatus.PENDING,
  },
  {
    id: 3,
    eventType: EventProgressStatus.PROFESSIONAL_EVENTS,
    customEvent: ProfessionalEventStatus.WORK_ANNIVERSARY,
    date: "2025-09-01 09:00:00",
    priority: EventPriorityStatus.MEDIUM,
    description: "Go to the gym",
    isReminedMe: ReminderModal.TRUE,
    eventStatus: EventStatus.COMPLETED,
  },
  {
    id: 4,
    eventType: EventProgressStatus.SOCIAL_EVENTS,
    customEvent: SocialEventStatus.WEDDING,
    date: "2025-07-31 14:45:00",
    priority: EventPriorityStatus.HIGH,
    description: "Family dinner",
    isReminedMe: ReminderModal.TRUE,
    eventStatus: EventStatus.PENDING,
  },
  {
    id: 5,
    eventType: EventProgressStatus.MISCELLANEOUS_EVENTS,
    customEvent: MiscellaneousEventStatus.APPOINTMENTS,
    date: "2025-10-05 16:00:00",
    priority: EventPriorityStatus.LOW,
    description: "Buy groceries",
    isReminedMe: ReminderModal.FALSE,
    eventStatus: EventStatus.COMPLETED,
  },
  {
    id: 6,
    eventType: EventProgressStatus.CUSTOM,
    customEvent: "Custom Type",
    date: "2025-08-20 11:30:00",
    priority: EventPriorityStatus.MEDIUM,
    description: "Birthday celebration",
    isReminedMe: ReminderModal.TRUE,
    eventStatus: EventStatus.PENDING,
  },
  {
    id: 7,
    eventType: EventProgressStatus.FESTIVALS_RELIGIOUS_EVENTS,
    customEvent: FestivalEventStatus.DIWALI_HOLI_CHRISTMAS,
    date: "2025-09-12 17:10:00",
    priority: EventPriorityStatus.HIGH,
    description: "Attend a meeting",
    isReminedMe: ReminderModal.FALSE,
    eventStatus: EventStatus.COMPLETED,
  },
  {
    id: 8,
    eventType: EventProgressStatus.PERSONAL_EVENTS,
    customEvent: PersonalEventStatus.ANNIVERSARY,
    date: "2025-11-03 12:00:00",
    priority: EventPriorityStatus.MEDIUM,
    description: "Go to the gym",
    isReminedMe: ReminderModal.TRUE,
    eventStatus: EventStatus.PENDING,
  },
  {
    id: 9,
    eventType: EventProgressStatus.PROFESSIONAL_EVENTS,
    customEvent: ProfessionalEventStatus.PROMOTIONS,
    date: "2025-12-24 20:45:00",
    priority: EventPriorityStatus.LOW,
    description: "Buy groceries",
    isReminedMe: ReminderModal.FALSE,
    eventStatus: EventStatus.COMPLETED,
  },
  {
    id: 10,
    eventType: EventProgressStatus.SOCIAL_EVENTS,
    customEvent: SocialEventStatus.PUBLIC_HOLIDAYS,
    date: "2025-08-15 10:00:00",
    priority: EventPriorityStatus.HIGH,
    description: "Birthday celebration",
    isReminedMe: ReminderModal.TRUE,
    eventStatus: EventStatus.PENDING,
  },
  {
    id: 11,
    eventType: EventProgressStatus.MISCELLANEOUS_EVENTS,
    customEvent: MiscellaneousEventStatus.TRAVEL_TRIP,
    date: "2025-09-10 19:00:00",
    priority: EventPriorityStatus.MEDIUM,
    description: "Attend a meeting",
    isReminedMe: ReminderModal.TRUE,
    eventStatus: EventStatus.COMPLETED,
  },
  {
    id: 12,
    eventType: EventProgressStatus.CUSTOM,
    customEvent: "Custom Type",
    date: "2025-10-18 22:30:00",
    priority: EventPriorityStatus.LOW,
    description: "Go to the gym",
    isReminedMe: ReminderModal.FALSE,
    eventStatus: EventStatus.PENDING,
  },
  {
    id: 13,
    eventType: EventProgressStatus.PROFESSIONAL_EVENTS,
    customEvent: ProfessionalEventStatus.TEAM_CELEBRATIONS,
    date: "2025-11-27 09:20:00",
    priority: EventPriorityStatus.HIGH,
    description: "Family dinner",
    isReminedMe: ReminderModal.TRUE,
    eventStatus: EventStatus.COMPLETED,
  },
  {
    id: 14,
    eventType: EventProgressStatus.SOCIAL_EVENTS,
    customEvent: SocialEventStatus.BIRTHDAY_PARTY,
    date: "2025-12-05 13:45:00",
    priority: EventPriorityStatus.MEDIUM,
    description: "Buy groceries",
    isReminedMe: ReminderModal.FALSE,
    eventStatus: EventStatus.PENDING,
  },
  {
    id: 15,
    eventType: EventProgressStatus.FESTIVALS_RELIGIOUS_EVENTS,
    customEvent: FestivalEventStatus.RAMZAN_LENT_NAVRATRI,
    date: "2025-08-28 15:30:00",
    priority: EventPriorityStatus.LOW,
    description: "Birthday celebration",
    isReminedMe: ReminderModal.TRUE,
    eventStatus: EventStatus.COMPLETED,
  },
];
