import {
  TaskProgressStatus,
  EventPriorityStatus,
  TaskAssignedStatus,
  TaskLabelStatus,
} from "./EnumAndOptions";

export const taskList = [
  {
    id: 1, // To show in table
    title: "Design Homepage",
    description: "Create initial layout and UI design for homepage.",
    status: TaskProgressStatus.IN_PROGRESS,
    priority: EventPriorityStatus.HIGH, // till here
    assignees: [
      TaskAssignedStatus.RAVI_KUMAR_JAIN,
      TaskAssignedStatus.AMARNATH_MISHRA,
      TaskAssignedStatus.HARSHAN_PANDEY,
    ],
    createdDate: "2025-07-01",
    updatedDate: "2025-07-15", // this one (optional)
    startDate: "2025-07-10",
    dueDate: "2025-07-25", // this one
    labels: [
      TaskLabelStatus.FRONTEND,
      TaskLabelStatus.BACKEND,
      TaskLabelStatus.AUTH,
    ],
  },
  {
    id: 2,
    title: "Setup Database Schema",
    description: "Design and implement database tables and relationships.",
    status: TaskProgressStatus.PENDING,
    priority: EventPriorityStatus.MEDIUM,
    assignees: [
      TaskAssignedStatus.HARSHAN_PANDEY,
      TaskAssignedStatus.AMARNATH_MISHRA,
    ],
    createdDate: "2025-07-02",
    updatedDate: "2025-07-02",
    startDate: "2025-07-20",
    dueDate: "2025-07-30",
    labels: [TaskLabelStatus.DATABASE, TaskLabelStatus.BACKEND],
  },
  {
    id: 3,
    title: "Write API Docs",
    description: "Document all endpoints with request/response examples.",
    status: TaskProgressStatus.COMPLETED,
    priority: EventPriorityStatus.LOW,
    assignees: [
      TaskAssignedStatus.AMARNATH_MISHRA,
      TaskAssignedStatus.RAVI_KUMAR_JAIN,
    ],
    createdDate: "2025-07-01",
    updatedDate: "2025-07-10",
    startDate: "2025-07-03",
    dueDate: "2025-07-09",
    labels: [TaskLabelStatus.DEVOPS, TaskLabelStatus.UI_UX],
  },
  {
    id: 4,
    title: "Create Login Page",
    description: "Build frontend and connect to auth service.",
    status: TaskProgressStatus.CANCELLED,
    priority: EventPriorityStatus.HIGH,
    assignees: [
      TaskAssignedStatus.VIJAY_MALHOTRA,
      TaskAssignedStatus.HARSHAN_PANDEY,
    ],
    createdDate: "2025-07-03",
    updatedDate: "2025-07-18",
    startDate: "2025-07-11",
    dueDate: "2025-07-27",
    labels: [TaskLabelStatus.FRONTEND, TaskLabelStatus.AUTH],
  },
  {
    id: 5,
    title: "Setup CI/CD",
    description: "Integrate GitHub Actions for build and deployment.",
    status: TaskProgressStatus.ON_HOLD,
    priority: EventPriorityStatus.MEDIUM,
    assignees: [
      TaskAssignedStatus.HARSHAN_PANDEY,
      TaskAssignedStatus.RAVI_KUMAR_JAIN,
    ],
    createdDate: "2025-07-04",
    updatedDate: "2025-07-04",
    startDate: "2025-07-21",
    dueDate: "2025-07-28",
    labels: [TaskLabelStatus.DATABASE, TaskLabelStatus.DEVOPS],
  },
  {
    id: 6,
    title: "Test Signup Flow",
    description: "Manual and automated testing of user signup.",
    status: TaskProgressStatus.COMPLETED,
    priority: EventPriorityStatus.HIGH,
    assignees: [
      TaskAssignedStatus.AMARNATH_MISHRA,
      TaskAssignedStatus.VIJAY_MALHOTRA,
    ],
    createdDate: "2025-07-05",
    updatedDate: "2025-07-12",
    startDate: "2025-07-06",
    dueDate: "2025-07-10",
    labels: [TaskLabelStatus.FRONTEND, TaskLabelStatus.DATABASE],
  },
  {
    id: 7,
    title: "Build Dashboard UI",
    description: "Create the main dashboard interface.",
    status: TaskProgressStatus.PENDING,
    priority: EventPriorityStatus.HIGH,
    assignees: [
      TaskAssignedStatus.VIJAY_MALHOTRA,
      TaskAssignedStatus.RAVI_KUMAR_JAIN,
    ],
    createdDate: "2025-07-06",
    updatedDate: "2025-07-20",
    startDate: "2025-07-14",
    dueDate: "2025-07-28",
    labels: [TaskLabelStatus.UI_UX, TaskLabelStatus.AUTH],
  },
  {
    id: 8,
    title: "Prepare Pitch Deck",
    description: "Design slides for product demo presentation.",
    status: TaskProgressStatus.IN_PROGRESS,
    priority: EventPriorityStatus.MEDIUM,
    assignees: [
      TaskAssignedStatus.AMARNATH_MISHRA,
      TaskAssignedStatus.HARSHAN_PANDEY,
    ],
    createdDate: "2025-07-07",
    updatedDate: "2025-07-07",
    startDate: "2025-07-22",
    dueDate: "2025-07-30",
    labels: [TaskLabelStatus.BACKEND, TaskLabelStatus.DATABASE],
  },
  {
    id: 9,
    title: "Setup Monitoring",
    description: "Integrate Sentry and Datadog for logging and metrics.",
    status: TaskProgressStatus.PENDING,
    priority: EventPriorityStatus.LOW,
    assignees: [TaskAssignedStatus.VIJAY_MALHOTRA],
    createdDate: "2025-07-08",
    updatedDate: "2025-07-08",
    startDate: "2025-07-25",
    dueDate: "2025-07-31",
    labels: [TaskLabelStatus.DEVOPS, TaskLabelStatus.UI_UX],
  },
  {
    id: 10,
    title: "User Feedback Survey",
    description: "Send out survey to beta users.",
    status: TaskProgressStatus.CANCELLED,
    priority: EventPriorityStatus.HIGH,
    assignees: [
      TaskAssignedStatus.AMARNATH_MISHRA,
      TaskAssignedStatus.RAVI_KUMAR_JAIN,
    ],
    createdDate: "2025-07-09",
    updatedDate: "2025-07-19",
    startDate: "2025-07-16",
    dueDate: "2025-07-26",
    labels: [TaskLabelStatus.FRONTEND, TaskLabelStatus.DEVOPS],
  },
  {
    id: 11,
    title: "Optimize Image Loading",
    description: "Implement lazy loading and compression.",
    status: TaskProgressStatus.COMPLETED,
    priority: EventPriorityStatus.LOW,
    assignees: [
      TaskAssignedStatus.AMARNATH_MISHRA,
      TaskAssignedStatus.VIJAY_MALHOTRA,
    ],
    createdDate: "2025-07-10",
    updatedDate: "2025-07-18",
    startDate: "2025-07-12",
    dueDate: "2025-07-17",
    labels: [TaskLabelStatus.AUTH],
  },
  {
    id: 12,
    title: "Fix Navbar Bug",
    description: "Navbar not collapsing on mobile.",
    status: TaskProgressStatus.IN_PROGRESS,
    priority: EventPriorityStatus.MEDIUM,
    assignees: [
      TaskAssignedStatus.AMARNATH_MISHRA,
      TaskAssignedStatus.RAVI_KUMAR_JAIN,
    ],
    createdDate: "2025-07-11",
    updatedDate: "2025-07-11",
    startDate: "2025-07-11",
    dueDate: "2025-07-12",
    labels: [TaskLabelStatus.UI_UX, TaskLabelStatus.FRONTEND],
  },
  {
    id: 13,
    title: "Add Dark Mode",
    description: "Provide toggle to switch to dark theme.",
    status: TaskProgressStatus.PENDING,
    priority: EventPriorityStatus.LOW,
    assignees: [TaskAssignedStatus.RAVI_KUMAR_JAIN],
    createdDate: "2025-07-12",
    updatedDate: "2025-07-12",
    startDate: "2025-07-26",
    dueDate: "2025-08-01",
    labels: [TaskLabelStatus.BACKEND, TaskLabelStatus.DATABASE],
  },
  {
    id: 14,
    title: "Email Integration",
    description: "Send notification emails via SendGrid.",
    status: TaskProgressStatus.ON_HOLD,
    priority: EventPriorityStatus.HIGH,
    assignees: [
      TaskAssignedStatus.VIJAY_MALHOTRA,
      TaskAssignedStatus.HARSHAN_PANDEY,
    ],
    createdDate: "2025-07-13",
    updatedDate: "2025-07-21",
    startDate: "2025-07-18",
    dueDate: "2025-07-27",
    labels: [TaskLabelStatus.DEVOPS, TaskLabelStatus.UI_UX],
  },
  {
    id: 15,
    title: "Write Unit Tests",
    description: "Add Jest tests for all core components.",
    status: TaskProgressStatus.COMPLETED,
    priority: EventPriorityStatus.MEDIUM,
    assignees: [
      TaskAssignedStatus.RAVI_KUMAR_JAIN,
      TaskAssignedStatus.HARSHAN_PANDEY,
    ],
    createdDate: "2025-07-14",
    updatedDate: "2025-07-14",
    startDate: "2025-07-22",
    dueDate: "2025-07-29",
    labels: [
      TaskLabelStatus.DEVOPS,
      TaskLabelStatus.UI_UX,
      TaskLabelStatus.AUTH,
    ],
  },
];
